package com.valvesoftware.steamlinkvr;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int bundled_in_assets = 0x7f010000;
        public static final int bundled_libs = 0x7f010001;
        public static final int load_local_libs = 0x7f010002;
        public static final int qt_libs = 0x7f010003;
        public static final int qt_sources = 0x7f010004;
    }

    public static final class drawable {
        public static final int res_0x7f020000_ic_launcher_background__0 = 0x7f020000;
        public static final int ic_launcher = 0x7f020001;
        public static final int ic_launcher_background = 0x7f020002;
    }

    public static final class layout {
        public static final int main = 0x7f030000;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f040000;
    }
}
