package com.valvesoftware.steamlinkvr;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int _ic_launcher_background__0_res_0x7f010000 = 0x7f010000;
        public static final int ic_launcher = 0x7f010001;
        public static final int ic_launcher_background = 0x7f010002;
    }

    public static final class layout {
        public static final int main = 0x7f020000;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f030000;
    }
}
