name: Execute

on:
    workflow_dispatch:
        inputs:
            app_id:
                description: 'app id to use'
                required: false
                default: ''
            version:
                description: 'Version to use with the app id'
                required: false
                default: ''
            force:
                description: 'Force Staging'
                type: choice
                options:
                    - true
                    - false
                required: false
                default: "false"
            download_source:
                description: 'google or apk-pure'
                type: choice
                options:
                    - google
                    - apk-pure
                required: false
                default: "google"

    repository_dispatch:
    schedule:
        - cron: '0 6 * * WED,THU,FRI,SAT'
        - cron: '0 6 * * TUE'

jobs:
    
    execute:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        environment: Execution
        concurrency:
            group: ${{ github.workflow }}
        steps:
            # Keeping this here in case we need more than 45GB of space in the future
            # - name: Maximize build space 
            #   uses: easimon/maximize-build-space@master 
            #   with: 
            #     swap-size-mb: 1024 
            #     remove-dotnet: 'true' 
            #     remove-android: 'true' 
            #     remove-haskell: 'true' 
            #     remove-codeql: 'true' 
            # - name: More space
            #   shell: bash
            #   run: |
            #     sudo rm -rf /usr/share/dotnet
            #     sudo rm -rf /usr/local/lib/android
            #     sudo rm -rf /opt/ghc
            #     sudo rm -rf /opt/hostedtoolcache/CodeQL
            - name: Set variables
              id: setvars
              run: |
                if [[ "${{github.event.schedule}}" == '0 6 * * WED,THU,FRI,SAT' ]]; then
                    echo "::set-output name=source::google"        
                elif [[ "${{github.event.schedule}}" == '0 6 * * TUE' ]]; then
                    echo "::set-output name=source::apk-pure"
                else
                    echo "::set-output name=source::${{ inputs.download_source }}"
                fi
            - uses: actions/checkout@v4
            - uses: docker://ghcr.io/lifeismana/steam-apk-watcher:latest
              env:
                FORCE: ${{ inputs.force }}
                APP_TO_PROCESS: ${{ inputs.app_id }}
                APP_VERSION: ${{ inputs.version }}
                SOURCE: ${{steps.setvars.outputs.source}}
                GOOGLE_MAIL: ${{secrets.GOOGLE_MAIL}}
                AAS_TOKEN: ${{secrets.AAS_TOKEN}}
                GIT_NAME: ${{ secrets.GIT_NAME}}
                GIT_EMAIL: ${{ secrets.GIT_EMAIL}}
